/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.ws.prak.auf5;

/**
 *
 * @author NetGhost03
 */
public class WeinAnlegenFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form WeinAnlegenFrame
     */
    public WeinAnlegenFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanelFormular1 = new javax.swing.JPanel();
        jBestellnummer1 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jName1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jFarbe1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLand1 = new javax.swing.JComboBox();
        jRegion1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jAlkoholgehalt1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jBSpeichern1 = new javax.swing.JButton();
        jBAbbrechen1 = new javax.swing.JButton();
        jPanelDiagramm1 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Wein anlegen");

        jTabbedPane2.setName(""); // NOI18N

        jBestellnummer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBestellnummer1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Bestellnummer");

        jLabel8.setText("Name");

        jFarbe1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Farbe");

        jLabel10.setText("Land");

        jLand1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jRegion1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jRegion1.setEnabled(false);

        jLabel11.setText("Region");

        jAlkoholgehalt1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("Alkoholgehalt");

        jBSpeichern1.setText("Speichern");

        jBAbbrechen1.setText("Abbrechen");

        javax.swing.GroupLayout jPanelFormular1Layout = new javax.swing.GroupLayout(jPanelFormular1);
        jPanelFormular1.setLayout(jPanelFormular1Layout);
        jPanelFormular1Layout.setHorizontalGroup(
            jPanelFormular1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormular1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanelFormular1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jBSpeichern1))
                .addGap(30, 30, 30)
                .addGroup(jPanelFormular1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jAlkoholgehalt1, 0, 100, Short.MAX_VALUE)
                    .addComponent(jRegion1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jName1)
                    .addComponent(jBestellnummer1)
                    .addComponent(jFarbe1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLand1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBAbbrechen1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanelFormular1Layout.setVerticalGroup(
            jPanelFormular1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormular1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanelFormular1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBestellnummer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormular1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormular1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFarbe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormular1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLand1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormular1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRegion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormular1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAlkoholgehalt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(39, 39, 39)
                .addGroup(jPanelFormular1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSpeichern1)
                    .addComponent(jBAbbrechen1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Weindaten", jPanelFormular1);

        javax.swing.GroupLayout jPanelDiagramm1Layout = new javax.swing.GroupLayout(jPanelDiagramm1);
        jPanelDiagramm1.setLayout(jPanelDiagramm1Layout);
        jPanelDiagramm1Layout.setHorizontalGroup(
            jPanelDiagramm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelDiagramm1Layout.setVerticalGroup(
            jPanelDiagramm1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab2", jPanelDiagramm1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBestellnummer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBestellnummer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBestellnummer1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jAlkoholgehalt1;
    private javax.swing.JButton jBAbbrechen1;
    private javax.swing.JButton jBSpeichern1;
    private javax.swing.JFormattedTextField jBestellnummer1;
    private javax.swing.JComboBox jFarbe1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox jLand1;
    private javax.swing.JTextField jName1;
    private javax.swing.JPanel jPanelDiagramm1;
    private javax.swing.JPanel jPanelFormular1;
    private javax.swing.JComboBox jRegion1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
